services:
  redis:
    image: redis:latest
    container_name: redis_container
    command: >
      --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  python_app:
    build: .
    container_name: python_app_container
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
